### ISSUE TITLE
how to resize the share screen window ?

### ISSUE THREAD

**Issue by xhb** [mynaparrot/plugNmeet-client#273]
i want to share a vscode window to students, but find out the share screen window is too small to view, how to resize it ??

![1667038587120](https://user-images.githubusercontent.com/3167082/198826173-d721fa33-5934-4b8a-bd51-ccc75c5920b8.jpg)

**Comment by jibon57** [comment]
That's from your end. Other user will see bigger screen. We set it smaller from presenter side for reducing mirror effect.
