### ISSUE TITLE
Will it be good to add a camera button on the screen with a microphone ,  Listen only ?

### ISSUE THREAD

**Issue by hembad** [mynaparrot/plugNmeet-client#308]
https://prnt.sc/Vce_u7sqa5dJ 

Will it be good to add a camera button on the screen with a microphone ,  Listen only ? as most of the conference portal provides it

**Comment by jibon57** [comment]
We don't have any plan to do that. We want to make it separated.

**Comment by hembad** [comment]
Thank you
