### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by DanDiborn** [mynaparrot/plugNmeet-client#326]
Hello! I would like to add a Russian translation. Ready to be directly involved and do all the basic translation work. Thank you!

**Comment by jibon57** [comment]
Thank you. I've added it! You can start from here: https://crowdin.com/project/plugnmeet-client

**Comment by DanDiborn** [comment]
Thanks for the quick cast! I'm getting to work on the translation.

**Comment by DanDiborn** [comment]
Hello! I finished the translation in full.

**Comment by jibon57** [comment]
Thanks
