### ISSUE TITLE
change default backgrounds for webcam views

### ISSUE THREAD

**Issue by jhjacobs81** [mynaparrot/plugNmeet-client#341]
The default settings have very cute backgrounds you can select, but what if i want different backgrounds?
I used the default installer, and i copied the new backgrounds to: /opt/plugNmeet/client/dist/assets/backgrounds
But they do not show up when i press the webcam icon. only the default ones.

**Comment by jibon57** [comment]
Please follow API: https://www.plugnmeet.org/docs/developer-guide/design-customisation

**Comment by jhjacobs81** [comment]
yes, i know this :) But im not meaning the background for the room, but for the webcam. 

So when i turn on the webcam, it doesnt show my hiddeous house, but a nice logo :)

**Comment by jibon57** [comment]
Oh! Sorry, you were talking about virtual background for webcam. You can upload during the session, otherwise you'll require to customize your client & use that customized version.

**Comment by jibon57** [comment]
You'll require to listed those name here: https://github.com/mynaparrot/plugNmeet-client/blob/a2d63d0b7be4b165a3068bf7a08882900a623e4a/src/components/virtual-background/helpers/backgroundHelper.ts#L12

Another trick to avoid customization. What you can do only replace the old image with your own image without changing the old file name. In this case you'll use same name but replace old image.

**Comment by jhjacobs81** [comment]
is there something else i need to do after i renamed them? i removed all but one image, but they all still show up in the client. do i need to reload the docker containers?

**Comment by jibon57** [comment]
need to restart the server
```service plugnmeet restart```

**Comment by jhjacobs81** [comment]
i restarted the whole server :) to no avail! in plug-n-meet settings from wordpress it says "local client" instead of "remote client" maybe thats the problem?

**Comment by jibon57** [comment]
Local client can be your own customized version, remote will be default with plugnmeet server. For your case as you changed in remote, should be select `remote client`
