### ISSUE TITLE
Picture in picture mode

### ISSUE THREAD

**Issue by vitaliybaran** [mynaparrot/plugNmeet-client#368]
When I choose a Picture in Picture mode and a little screen appears above all other tabs, the video in the little screen freezes after some seconds and when I get back to the original sessiob tab, the little screen is live again. It freezes over all the tabs. It works only over the original tab. Is it only the case with my moodle plugin?
I use ready-to-use [plugNmeet cloud solution](https://www.plugnmeet.cloud/) api. free account.

**Comment by jibon57** [comment]
I've opened a pull request here: https://github.com/livekit/client-sdk-js/pull/617

**Comment by jibon57** [comment]
@vitaliybaran is it possible you to test from here?

https://deploy-preview-378--plugnmeet.netlify.app/login

**Comment by vitaliybaran** [comment]
> @vitaliybaran is it possible you to test from here?
> 
> https://deploy-preview-378--plugnmeet.netlify.app/login

Hi there, I tested PiP on this link with my students. Unfortunately it is as it was. The problem persists. The picture freezes over other tabs. Plus when I ruturn to the "Meeting tab" the picture does not come alive untill I leave the PiP mode. Foremely it was enough to return to the meeting tab for the picture to come alive.

**Comment by jibon57** [comment]
@vitaliybaran please check from: https://demo.plugnmeet.com/login.html . Problem should be solved. We'll publish that for cloud soon.

**Comment by vitaliybaran** [comment]
> @vitaliybaran please check from: https://demo.plugnmeet.com/login.html . Problem should be solved. We'll publish that for cloud soon.

@jibon57 Seems to be working smoothly now.
