### ISSUE TITLE
No sound when the screen or browser tab is shared

### ISSUE THREAD

**Issue by vitaliybaran** [mynaparrot/plugNmeet-client#401]
No sound is heard by students when I share my entire screen with audio. The same is true for browser tab sharing - students hear no sound.

**Comment by jibon57** [comment]
This is the problem with latest version of Google Chrome. No solution so far.

**Comment by vitaliybaran** [comment]
MS Edge as well? because no sound here either.

**Comment by jibon57** [comment]
Edge is also Chrome

**Comment by jibon57** [comment]
As a work around you can join as another user & share screen.

**Comment by jibon57** [comment]
Sorry for misunderstanding. This is browser related settings which will require to enable before share screen. By default it's disable: https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/suppressLocalAudioPlayback
I think it's better to disable otherwise there will be echo.
