### ISSUE TITLE
participant can't share the ppt file in the whiteboard When you join a meeting midway,

### ISSUE THREAD

**Issue by wujianqiangwjq** [mynaparrot/plugNmeet-client#506]
When you join a meeting midway, the whiteboard content cannot be shared (this Presenter sharing  the second page)

**Comment by wbobteng** [comment]
@wujianqiangwjq  Do you mean that you are doing a meeting and use the whiteboard to make some presentation, during the meeting, someone joined ( for example, 20 minutes later than you start)  then this particular user can not see the changes you did on the whiteboard? Is this the situation?  Just trying to understand and see if we can reproduce the issue in our end or not. Thanks

**Comment by wujianqiangwjq** [comment]
yes

**Comment by wujianqiangwjq** [comment]
![a](https://github.com/mynaparrot/plugNmeet-client/assets/20573480/f65b04e3-c87a-4ab4-a9f4-b76649a1390e)
 wjq  as Presenter

**Comment by wujianqiangwjq** [comment]
<img width="956" alt="b" src="https://github.com/mynaparrot/plugNmeet-client/assets/20573480/216b4795-7d7b-40f1-be1f-6ab7fa8ea4da">
zhangwei as participant

**Comment by wujianqiangwjq** [comment]
Zhangwei join meet  at the Wjq share the second page.

**Comment by jibon57** [comment]
In this type situation instruct other user (who can't see) to close whiteboard & reopen by click on bottom icon. This way whiteboard will sync.

**Comment by wujianqiangwjq** [comment]
will sync, but the displayed image is invalid,Because after going online, the ppt resources were not obtained

**Comment by jibon57** [comment]
I wasn't reproduce it in latest version. Working fine from my end.

**Comment by wujianqiangwjq** [comment]
Thank you, the latest  version is ok
