### ISSUE TITLE
Cannot hear others when I minimize the webview on iOS

### ISSUE THREAD

**Issue by r0se9** [mynaparrot/plugNmeet-client#653]
I forked this repo and hosted my local server.
Then I noticed that I couldn't hear others voice and other can hear my voice when I minimize the webview on iOS.
It's okay on the desktop but only on mobile.
When I was using the former version(v1.x) for livekit, it was okay.

**Comment by jibon57** [comment]
Safari browser is recommended. Please check readme file.
