### ISSUE TITLE
need token

### ISSUE THREAD

**Issue by huashuiwujiale** [mynaparrot/plugNmeet-client#802]
I have deployed PLUG_SERVER. I don not know how to use plugNmeet-client. I set config.js window.PLUG_N_MEET_SERVER_URL = 'http://xxxx.4440.top';Then I run pnpm start, it say need token

<img width="1230" alt="image" src="https://github.com/user-attachments/assets/02f8dca1-de2c-4810-ba27-b8719b704c2f">

**Comment by jibon57** [comment]
You can either use API or for testing:  http://localhost:3000/login
